spring:
  datasource:
    url: jdbc:mysql://34.87.236.86:3306/safe_scan?useSSL=false
    username: root-safe-scan
    password: 123456
  data:
    redis:
      host: 10.128.187.163
      port: 6379

app:
  uploadAvatars:
    dir: /srv/safe_scan/avatars
  uploadVideos:
    dir: /srv/safe_scan/videos