spring:
  datasource:
    url: jdbc:mysql://35.189.30.89:3306/safe_scan?useSSL=false
    username: root
    password: 123456
  data:
    redis:
      host: 10.55.177.219
      port: 6379

app:
  uploadAvatars:
    dir: /srv/safe_scan/avatars
  uploadVideos:
    dir: /srv/safe_scan/videos
  generatedKeyFrame:
    dir: /srv/safe_scan/py