spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  profiles:
    active: dev

mybatis:
  configuration:
    map-underscore-to-camel-case: true